### ISSUE TITLE
Pattern matching error

### ISSUE THREAD

**Issue by Mirivan** [AetherMagee/AetherManager#5]
_Не желательно_ использовать replace при обрезке паттерна. Можно использовать встроенную функцию группировки из библиотеки.

`pattern="сколько будет(?: |$)(.*)"`
`event.pattern_match.group(0)`

также

`event.text.split("сколько будет ")[1]`

**Comment by AetherMagee** [comment]
Too lazy to rewrite all the functions on one of those patterns, but ty for a pice of advice, will use it in the future

**Comment by Mirivan** [comment]
> Too lazy to rewrite all the functions on one of those patterns, but ty for a piece of advice, will use it in the future

похуй
